databases:
  - name: food_truck_production
    databaseName: food_truck_production
    user: food_truck_user
    region: singapore

services:
  - type: web
    name: food_truck_production
    env: ruby
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: <%= ENV['DATABASE_URL'] %>
        fromDatabase:
          name: food-truck
          property: connectionString
      - key: <%= ENV['RAILS_MASTER_KEY'] %>
        sync: false